server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  jackson:
    time-zone: GMT+8


  data:
    # Redis配置
    redis:
      database: 0 # 默认数据库索引
      host: 127.0.0.1 # Redis服务器地址
      port: 6379 # Redis服务器端口
      password: abc123456 # Redis服务器密码
      jedis:
        pool:
          max-active: 100 # 最大活动连接数
          max-wait: -1ms # 最大等待时间
          max-idle: 16 # 最大空闲连接数
          min-idle: 8 # 最小空闲连接数


#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true

aliyun:
  sms:
    access-key-id:  LTAI5tHr279wMdGMnuYM7UtB
    access-key-secret: ufSZWjyVK2M6Wl8NW2nQNbnqmCfvCo
    endpoint: dysmsapi.aliyuncs.com

knife4j:
  enable: true